### ISSUE TITLE
Added Value Over ECS?

### ISSUE THREAD

**Issue by rjhintz** [coldbrewcloud/coldbrew-cli#8]
It would be helpful to give some explanation of the added value of coldbrew over native ECS.

**Comment by WillLiu360** [comment]
agreed.

**Comment by d5** [comment]
This is basically an automation tool, and, I believe for many people, it can unlock: 
- faster access to ECS (jumpstart with little knowledge on AWS specifics)
- low maintenance costs (most cases you don't even need AWS console or SDK)
- less mistakes by removing boring repetitions
- easier to integrate with CI (single binary executable and config file is all you need; also easier standardization)

I've been using ECS in many production projects for years. After trying several different approaches, use cases, and requirements, I saw some patterns that could be automated. And that's why I built this tool. Probably this is still early version, but, I've already used this tool for my last 2 backend services with no issues.

Hope this answered your questions?

Btw, as you said, it's a good idea to document this somewhere. Thanks!

**Comment by rjhintz** [comment]
@d5  Thanks for the clarification. 

If you like, I'd do a simple pull request that will add what you said, with a little editing, to the README. Then we can close this. If you want to do it yourself, no problem.

**Comment by d5** [comment]
@rjhintz Sure!
